name: Manter CotacoesForex Vivo

on:
  schedule:
    # Executa a cada 6 horas (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Permite execução manual para testes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar Requisição HTTP
        run: |
          curl -H "User-Agent: Mozilla/5.0" https://cotacoesforex.streamlit.app/
